modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/naari3/offers-hud/issues"

[[mods]]
modId = "offershud"
version = "${version}"
displayName = "OffersHUD"
authors = "naari3"
description = '''
Focusing on a villager will show a list of trades.
'''
logoFile = "assets/offershud/icon.png"
displayURL = "https://github.com/naari3/offers-hud"

[[mixins]]
config = "offershud.mixins.json"

[[dependencies.offershud]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.offershud]]
modId = "minecraft"
type = "required"
versionRange = "${mc_deps_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.offershud]]
modId = "cloth_config"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
